### PR TITLE
fix: insert snippet without replacing original html

### LINKED ISSUE #3: Replacement of </body> tag inverts </body> and </html>
Without this plugin, my HTML output ends with:

```html
</body>
</html>
```

With this plugin installed, regardless of whether the `pechente.kirby-admin-bar.active` option is true or false, it ends up as:

```html
[admin-bar code]
</html>
</body>
```

It's a bug in this line:

https://github.com/Pechente/kirby-admin-bar/blob/27ed722608e115e313f7ab72e4fbc607a9815d1a/index.php#L14

This code first does a replacement resulting in this string:

```html
[admin-bar code]
</html>
```

then it appends `</body>` at the end of that string.

This can be fixed by moving the `. '</body>'` to `snippet('admin-bar', [], true) . '</body>'`.

But there are other possible issues with this replacement code, so I'll try to make a pull request with a more complete fix.

### PR DESCRIPTION
**Pull request by fvsch**
Fixes #3.

### CODE REVIEW

File: index.php [hunk 1]
```diff
@@ -10,10 +10,17 @@
     ],
     'hooks' => [
         'page.render:after' => function ($contentType, $data, $html) {
-            if ($contentType === 'html') {
-                $html = str_replace('</body>', snippet('admin-bar', [], true), $html) . '</body>';
+            if ($contentType !== 'html') return;
```
Comment (fvsch) [inline index.php:13]: As far as I know, if you don't return a string then Kirby keeps the original HTML.
This lets us use early returns and avoid having to `return $html`.

If that's less clear than the original code, I can revert it.

File: index.php [hunk 2]
```diff
@@ -10,10 +10,17 @@
...
+
+            // find last occurrence of end tag
+            $pos = strripos($html, '</body>');
+            if ($pos === false) $pos = strripos($html, '</html>');
```
Comment (fvsch) [inline index.php:17]: The original code would replace the first occurrence of `</body>` in the original HTML. This would fail if:

- The original HTML has the string `</body>` more than once (which is possible if you have some JavaScript strings or HTML in `<script>` or `<template>` elements. Fix: look for the last instance.
- The original HTML used a different case, like `</Body>` or `</BODY>` (uncommon these days, but valid). Fix: use case-insensitive search.

This also falls back to looking for `</html>` if `</body>` was not found. (The result would not be valid HTML but it would still be parsed correctly by browsers.)

File: index.php [hunk 3]
```diff
@@ -10,10 +10,17 @@
...
+
+            // insert snippet before end tag
+            if ($pos !== false) {
+                $bar = snippet('admin-bar', [], true);
+                return substr_replace($html, $bar, $pos, 0);
```
Comment (fvsch) [inline index.php:22]: Using `substr_replace` with the position of the occurrence of `</body>` (or `</html>`) that we found, and a length of `0`, means that we are inserting the replacement string at the desired position but not replacing any character in the original string.

This makes the issue in #3 impossible.

**Review by fvsch — COMMENTED** [review]
This works pretty well for me locally.

I'm wondering if it should use `mb_*` variants of the string functions (`mb_substr_replace` instead of `substr_replace`, etc.). It looks like that's not strictly necessary here, but it probably doesn't hurt much to use the mb functions instead.
